/net/scratch/caom/dplm_env/lib/python3.9/site-packages/lightning_fabric/__init__.py:40: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
[rank: 0] Seed set to 42
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/parsing.py:199: Attribute 'model' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['model'])`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/lightning_fabric/connector.py:563: `precision=16` is supported for historical reasons but its usage is discouraged. Please set your precision to 16-mixed instead!
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
You are using a CUDA device ('NVIDIA A100 80GB PCIe') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:652: Checkpoint directory /home/caom/AID3/dplm/pronet_vae_approach/scripts/checkpoints exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type                 | Params
-----------------------------------------------
0 | model | SimpleProNetVAEModel | 527 K 
-----------------------------------------------
527 K     Trainable params
0         Non-trainable params
527 K     Total params
2.110     Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7395. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6793. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6190. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5960. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4209. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2586. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3919. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2968. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5393. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5742. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5700. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5435. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3570. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3892. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3038. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3903. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6548. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5949. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6442. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3643. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4820. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4168. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5323. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5497. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5406. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4964. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4289. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5110. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3494. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7788. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6088. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5718. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 9810. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4385. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4423. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2447. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5976. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5250. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4825. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4215. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8052. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5595. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4844. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5304. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5094. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5538. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6467. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5217. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4985. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4945. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2262. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3630. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3755. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6115. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6672. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2991. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6600. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4298. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3629. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5458. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6992. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6069. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3868. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4091. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3108. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5479. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3049. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4922. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 9860. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3972. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4082. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2778. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4917. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5779. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6124. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6131. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5719. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4834. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5896. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2433. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4193. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6245. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4760. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6708. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4739. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3859. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6980. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3881. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6885. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3424. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7435. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5924. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5446. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7961. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8215. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3442. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4387. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4284. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2527. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6450. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5040. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7173. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5730. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3810. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4686. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6904. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6926. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3753. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4500. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3863. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5383. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5725. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4802. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4833. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 9035. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5067. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4330. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6310. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7730. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4057. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6109. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8089. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4852. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6272. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3497. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5259. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2199. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4246. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4729. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7089. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6495. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5429. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4950. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4227. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6546. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4846. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7267. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5778. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3279. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4689. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3394. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5608. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4892. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5537. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5147. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4659. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5570. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5031. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2674. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5453. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4015. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4632. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5978. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7411. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7819. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3001. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5117. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4630. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7250. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3423. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3622. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3976. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4151. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2922. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5477. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5639. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5053. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5314. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5482. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6912. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5904. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6859. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4548. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4641. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2831. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5921. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6680. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4850. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2136. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4179. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5556. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5334. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3895. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3315. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5072. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5485. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5036. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5141. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4392. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5443. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6046. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 9564. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7263. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5088. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4591. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5384. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4502. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4416. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4895. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5876. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6727. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3894. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4987. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4588. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5908. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5961. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5267. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4259. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6236. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7205. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4411. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6141. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3304. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4546. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5164. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5589. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6185. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3683. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5114. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3638. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3537. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4233. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4752. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5237. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6426. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5596. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6193. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5832. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5320. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2793. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3119. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5813. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6392. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5111. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4436. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5341. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5098. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6946. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5470. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5457. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4029. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6567. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4482. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6160. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2743. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3536. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7862. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4366. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4072. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4426. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2643. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3389. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3980. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3584. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4697. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6282. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8130. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4517. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5548. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4374. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4031. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6437. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4504. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3672. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3157. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8172. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3312. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7002. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5439. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6634. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3893. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6201. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7128. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5865. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3343. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4272. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5771. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4043. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5022. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5112. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4995. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5776. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4421. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6157. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4524. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7613. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5065. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3653. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4613. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4522. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4119. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4012. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2910. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3821. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3479. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3472. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4358. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4110. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4395. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6023. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3992. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5967. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2956. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2860. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6611. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5116. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2655. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5328. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8697. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2758. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6118. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7003. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6053. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4516. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7408. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6043. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5752. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4118. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5507. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5128. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8442. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5007. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5720. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4125. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4855. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8264. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5277. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6693. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4596. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3511. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3172. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4616. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7081. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5734. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4048. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7058. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4480. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3546. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4266. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7138. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3942. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2463. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2678. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3080. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4303. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3115. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5895. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4531. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4907. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4566. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4478. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4313. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5286. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5969. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7123. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2468. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6142. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3746. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3563. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3968. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4005. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4974. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2737. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5187. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5392. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3744. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4382. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7554. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3362. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6134. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4996. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5154. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5686. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3667. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3550. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5696. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4711. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4062. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5849. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3451. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5241. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5275. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8536. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5615. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 9346. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6886. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4247. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3223. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5402. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4372. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5102. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5266. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6350. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6318. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5189. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4563. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4580. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5017. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4079. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3795. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5244. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3685. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6354. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4037. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3786. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3743. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6657. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5991. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5540. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4921. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6328. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8369. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3814. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8486. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3175. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6179. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5287. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4706. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6645. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4148. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5657. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4386. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5604. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2358. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3836. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4021. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3807. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6406. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6975. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4957. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5019. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4187. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3152. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2158. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6045. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3835. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4940. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5227. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4458. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4228. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4277. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5467. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5387. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3488. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5723. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5378. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 8136. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2494. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6976. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5280. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3986. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4391. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3576. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4451. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2597. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4628. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6925. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5798. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4672. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6203. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5815. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3879. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4365. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4674. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6037. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3858. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6362. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5909. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6460. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6812. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4633. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3449. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4393. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5853. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5423. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7225. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4050. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7176. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5625. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6296. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7956. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5310. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5611. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3413. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6196. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4785. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4412. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5010. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7356. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6872. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2617. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5064. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4519. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3910. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6006. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5302. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3677. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5175. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4056. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2698. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6668. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5233. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5903. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4301. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3306. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6606. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1860. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4676. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5162. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6183. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5855. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5381. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5577. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4786. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4486. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7168. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6202. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5249. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5520. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6002. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5171. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5468. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4753. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4302. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6371. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5376. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6067. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6423. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6299. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5603. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6359. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4994. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3991. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5373. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6690. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6104. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5101. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2800. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4553. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4004. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4136. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3923. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5464. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1802. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5866. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4707. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5586. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4335. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5437. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2913. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5859. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 7611. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 5493. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4803. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4208. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3491. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6513. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6825. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 6152. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 3087. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
`Trainer.fit` stopped: `max_epochs=100` reached.
Traceback (most recent call last):
  File "/home/caom/AID3/dplm/pronet_vae_approach/scripts/train_simple.py", line 443, in <module>
    main() 
  File "/home/caom/AID3/dplm/pronet_vae_approach/scripts/train_simple.py", line 440, in main
    trainer.test(lightning_module, datamodule)
  File "/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 753, in test
    return call._call_and_handle_interrupt(
  File "/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 793, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 936, in _run
    _verify_loop_configurations(self)
  File "/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 42, in _verify_loop_configurations
    __verify_eval_loop_configuration(model, "test")
  File "/net/scratch/caom/dplm_env/lib/python3.9/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 110, in __verify_eval_loop_configuration
    raise MisconfigurationException(f"No `{step_name}()` method defined to run `Trainer.{trainer_method}`.")
lightning_fabric.utilities.exceptions.MisconfigurationException: No `test_step()` method defined to run `Trainer.test`.
